/**
 * Google Calendar Service - Zion Recruit
 * Integration with Google Calendar API for interview scheduling
 * 
 * Note: Requires 'googleapis' package to be installed for full functionality.
 * When not installed, methods will throw appropriate errors.
 */

// ============================================
// Types
// ============================================

export interface CalendarEvent {
  id: string;
  summary: string;
  description?: string;
  start: {
    dateTime: string;
    timeZone: string;
  };
  end: {
    dateTime: string;
    timeZone: string;
  };
  attendees: Array<{
    email: string;
    name?: string;
    responseStatus?: "needsAction" | "declined" | "tentative" | "accepted";
  }>;
  conferenceData?: {
    createRequest?: {
      requestId: string;
      conferenceSolutionKey: {
        type: "hangoutsMeet";
      };
    };
  };
  location?: string;
  reminders?: {
    useDefault: boolean;
    overrides?: Array<{
      method: "email" | "popup";
      minutes: number;
    }>;
  };
}

export interface InterviewScheduleInput {
  candidateName: string;
  candidateEmail: string;
  jobTitle: string;
  startTime: Date;
  durationMinutes: number;
  interviewerEmails: string[];
  location?: string;
  notes?: string;
  createMeetLink?: boolean;
}

export interface ScheduledEvent {
  id: string;
  htmlLink: string;
  hangoutLink?: string;
  summary: string;
  start: string;
  end: string;
  status: string;
}

// ============================================
// Google Calendar Service Class
// ============================================

class GoogleCalendarService {
  private oauth2Client: any | null = null;
  private calendar: any | null = null;
  private google: any = null;

  /**
   * Initialize with OAuth2 credentials
   * Dynamically imports googleapis to avoid build errors
   */
  async initialize(credentials: {
    clientId: string;
    clientSecret: string;
    redirectUri: string;
  }): Promise<boolean> {
    try {
      // Dynamic import
      const { google } = await import("googleapis");
      this.google = google;
      
      this.oauth2Client = new google.auth.OAuth2(
        credentials.clientId,
        credentials.clientSecret,
        credentials.redirectUri
      );

      this.calendar = google.calendar({ version: "v3", auth: this.oauth2Client });
      return true;
    } catch (error) {
      console.error("Failed to initialize Google Calendar service:", error);
      console.error("Make sure 'googleapis' package is installed: npm install googleapis");
      return false;
    }
  }

  /**
   * Check if service is initialized
   */
  isInitialized(): boolean {
    return this.calendar !== null;
  }

  /**
   * Set access token
   */
  setAccessToken(accessToken: string, refreshToken?: string) {
    if (!this.oauth2Client) {
      throw new Error("OAuth2 client not initialized. Call initialize() first.");
    }

    this.oauth2Client.setCredentials({
      access_token: accessToken,
      refresh_token: refreshToken,
    });
  }

  /**
   * Generate OAuth2 authorization URL
   */
  getAuthUrl(): string {
    if (!this.oauth2Client) {
      throw new Error("OAuth2 client not initialized. Call initialize() first.");
    }

    return this.oauth2Client.generateAuthUrl({
      access_type: "offline",
      scope: [
        "https://www.googleapis.com/auth/calendar",
        "https://www.googleapis.com/auth/calendar.events",
      ],
      prompt: "consent",
    });
  }

  /**
   * Exchange authorization code for tokens
   */
  async getTokensFromCode(code: string): Promise<{
    access_token: string;
    refresh_token: string | undefined;
    expiry_date: number | undefined;
  }> {
    if (!this.oauth2Client) {
      throw new Error("OAuth2 client not initialized. Call initialize() first.");
    }

    const { tokens } = await this.oauth2Client.getToken(code);

    return {
      access_token: tokens.access_token || "",
      refresh_token: tokens.refresh_token,
      expiry_date: tokens.expiry_date,
    };
  }

  /**
   * Schedule an interview
   */
  async scheduleInterview(input: InterviewScheduleInput): Promise<ScheduledEvent> {
    if (!this.calendar) {
      throw new Error("Calendar service not initialized. Call initialize() first.");
    }

    const endTime = new Date(input.startTime.getTime() + input.durationMinutes * 60000);

    const event: CalendarEvent = {
      id: "", // Will be generated by Google
      summary: `Entrevista: ${input.candidateName} - ${input.jobTitle}`,
      description: `Entrevista com ${input.candidateName} para a vaga de ${input.jobTitle}.\n\n${input.notes || ""}`,
      start: {
        dateTime: input.startTime.toISOString(),
        timeZone: "America/Sao_Paulo",
      },
      end: {
        dateTime: endTime.toISOString(),
        timeZone: "America/Sao_Paulo",
      },
      attendees: [
        { email: input.candidateEmail, name: input.candidateName },
        ...input.interviewerEmails.map((email) => ({ email })),
      ],
      location: input.location,
      reminders: {
        useDefault: false,
        overrides: [
          { method: "email", minutes: 24 * 60 }, // 1 day before
          { method: "popup", minutes: 30 }, // 30 minutes before
        ],
      },
    };

    // Add Google Meet link if requested
    if (input.createMeetLink) {
      event.conferenceData = {
        createRequest: {
          requestId: `zion-${Date.now()}`,
          conferenceSolutionKey: {
            type: "hangoutsMeet",
          },
        },
      };
    }

    const response = await this.calendar.events.insert({
      calendarId: "primary",
      requestBody: event,
      conferenceDataVersion: input.createMeetLink ? 1 : 0,
      sendUpdates: "all",
    });

    const createdEvent = response.data;

    return {
      id: createdEvent.id || "",
      htmlLink: createdEvent.htmlLink || "",
      hangoutLink: createdEvent.hangoutLink,
      summary: createdEvent.summary || "",
      start: createdEvent.start?.dateTime || createdEvent.start?.date || "",
      end: createdEvent.end?.dateTime || createdEvent.end?.date || "",
      status: createdEvent.status || "",
    };
  }

  /**
   * Get available time slots
   */
  async getAvailableSlots(
    startDate: Date,
    endDate: Date,
    durationMinutes: number = 60
  ): Promise<Array<{ start: Date; end: Date }>> {
    if (!this.calendar) {
      throw new Error("Calendar service not initialized. Call initialize() first.");
    }

    // Get busy times
    const response = await this.calendar.freebusy.query({
      requestBody: {
        timeMin: startDate.toISOString(),
        timeMax: endDate.toISOString(),
        items: [{ id: "primary" }],
      },
    });

    const busySlots = response.data.calendars?.primary?.busy || [];

    // Generate available slots (9 AM to 6 PM on weekdays)
    const availableSlots: Array<{ start: Date; end: Date }> = [];
    const current = new Date(startDate);

    while (current < endDate) {
      // Skip weekends
      if (current.getDay() !== 0 && current.getDay() !== 6) {
        // Check each hour from 9 AM to 6 PM
        for (let hour = 9; hour < 18; hour++) {
          const slotStart = new Date(current);
          slotStart.setHours(hour, 0, 0, 0);

          const slotEnd = new Date(slotStart);
          slotEnd.setMinutes(slotEnd.getMinutes() + durationMinutes);

          // Check if slot overlaps with any busy time
          const isBusy = busySlots.some((busy: { start?: string; end?: string }) => {
            const busyStart = new Date(busy.start || 0);
            const busyEnd = new Date(busy.end || 0);
            return slotStart < busyEnd && slotEnd > busyStart;
          });

          if (!isBusy && slotEnd < endDate) {
            availableSlots.push({ start: slotStart, end: slotEnd });
          }
        }
      }

      // Move to next day
      current.setDate(current.getDate() + 1);
    }

    return availableSlots;
  }

  /**
   * Cancel an event
   */
  async cancelEvent(eventId: string, reason?: string): Promise<void> {
    if (!this.calendar) {
      throw new Error("Calendar service not initialized. Call initialize() first.");
    }

    await this.calendar.events.delete({
      calendarId: "primary",
      eventId,
      sendUpdates: "all",
    });
  }

  /**
   * Update an event
   */
  async updateEvent(
    eventId: string,
    updates: Partial<CalendarEvent>
  ): Promise<ScheduledEvent> {
    if (!this.calendar) {
      throw new Error("Calendar service not initialized. Call initialize() first.");
    }

    const response = await this.calendar.events.update({
      calendarId: "primary",
      eventId,
      requestBody: updates,
      sendUpdates: "all",
    });

    const updatedEvent = response.data;

    return {
      id: updatedEvent.id || "",
      htmlLink: updatedEvent.htmlLink || "",
      hangoutLink: updatedEvent.hangoutLink,
      summary: updatedEvent.summary || "",
      start: updatedEvent.start?.dateTime || updatedEvent.start?.date || "",
      end: updatedEvent.end?.dateTime || updatedEvent.end?.date || "",
      status: updatedEvent.status || "",
    };
  }

  /**
   * Get event details
   */
  async getEvent(eventId: string): Promise<ScheduledEvent> {
    if (!this.calendar) {
      throw new Error("Calendar service not initialized. Call initialize() first.");
    }

    const response = await this.calendar.events.get({
      calendarId: "primary",
      eventId,
    });

    const event = response.data;

    return {
      id: event.id || "",
      htmlLink: event.htmlLink || "",
      hangoutLink: event.hangoutLink,
      summary: event.summary || "",
      start: event.start?.dateTime || event.start?.date || "",
      end: event.end?.dateTime || event.end?.date || "",
      status: event.status || "",
    };
  }
}

// Export singleton instance
export const googleCalendarService = new GoogleCalendarService();

// ============================================
// Utility Functions
// ============================================

/**
 * Format date for display
 */
export function formatEventDate(date: Date | string): string {
  const d = typeof date === "string" ? new Date(date) : date;
  return d.toLocaleString("pt-BR", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/**
 * Generate available slot times for next N days
 */
export function generateDefaultSlots(days: number = 7): Array<{
  date: string;
  slots: string[];
}> {
  const result: Array<{ date: string; slots: string[] }> = [];
  const now = new Date();

  for (let i = 0; i < days; i++) {
    const date = new Date(now);
    date.setDate(date.getDate() + i);

    // Skip weekends
    if (date.getDay() === 0 || date.getDay() === 6) continue;

    const slots: string[] = [];
    for (let hour = 9; hour < 18; hour++) {
      slots.push(`${hour.toString().padStart(2, "0")}:00`);
    }

    result.push({
      date: date.toISOString().split("T")[0],
      slots,
    });
  }

  return result;
}
